// ============================================================
// NBTI 16 人格原型 v2.0
// 新增 mbtiAffinity: 每个人格与哪些 MBTI 类型有亲和关系
// 算法会优先在亲和的 MBTI 类型中匹配，大幅提高分布均匀性
// ============================================================

export const archetypes = [
  {
    id: 'late-bomb',
    code: 'LATE',
    title: '延迟爆破者',
    hook: '你不是当场发作，你是回家复盘完再精准补刀。',
    systemRemark: '系统判断你情绪上线不快，但报复链路极其清晰。',
    friendshipWarning: '朋友和你吵完架，真正的危机通常在第二天早上。',
    selfAwareDisclaimer: '你嘴上说算了，多半只是先去攒证据。',
    shareSnippet: '我是 NBTI 的延迟爆破者，表面放过，内心立案。',
    dimensionBias: ['spite', 'filter'],
    mbtiAffinity: ['ISTJ', 'INTJ', 'ISFJ'],
  },
  {
    id: 'room-freezer',
    code: 'FREE',
    title: '气氛冷冻机',
    hook: '你不一定爱说话，但你很会让别人突然开始斟酌措辞。',
    systemRemark: '系统检测到你具备轻微沉默威慑。',
    friendshipWarning: '朋友聚会里最怕你忽然说一句"那也行吧"。',
    selfAwareDisclaimer: '你不是凶，你只是有一种让人自动反思的平静。',
    shareSnippet: '我是 NBTI 的气氛冷冻机，不张嘴也能让场面降温。',
    dimensionBias: ['gravity', 'mask'],
    mbtiAffinity: ['INTJ', 'ISTJ', 'ENTJ'],
  },
  {
    id: 'chaos-host',
    code: 'HOST',
    title: '整活主持人',
    hook: '只要场面一无聊，你就会主动把局搅出节目效果。',
    systemRemark: '系统确认你具备稳定制造热闹的危险倾向。',
    friendshipWarning: '朋友跟你出门前，最好默认今天不会完全按计划收场。',
    selfAwareDisclaimer: '你不是不成熟，你只是拒绝让场子死掉。',
    shareSnippet: '我是 NBTI 的整活主持人，安静对我来说像工伤。',
    dimensionBias: ['chaos', 'orbit'],
    mbtiAffinity: ['ENFP', 'ENTP', 'ESFP'],
  },
  {
    id: 'mercy-manager',
    code: 'MERC',
    title: '仁慈经理人',
    hook: '你表面给台阶，实则把每个人的表现都记进心里周报。',
    systemRemark: '系统判断你非常会维持表面和气。',
    friendshipWarning: '朋友会觉得你很好说话，直到你开始减少投入。',
    selfAwareDisclaimer: '你很少翻脸，不代表你真的没记账。',
    shareSnippet: '我是 NBTI 的仁慈经理人，嘴上和气，心里绩效。',
    dimensionBias: ['mask', 'spite'],
    mbtiAffinity: ['ENFJ', 'INFJ', 'ESFJ'],
  },
  {
    id: 'wild-mic',
    code: 'MIC',
    title: '失控麦克风',
    hook: '你的想法不是先过滤，而是先公放。',
    systemRemark: '系统提示你的语言制动模块偶尔不在岗。',
    friendshipWarning: '朋友带你见新人的时候，心率通常不会太平稳。',
    selfAwareDisclaimer: '你不是故意伤人，你只是比后悔先开口。',
    shareSnippet: '我是 NBTI 的失控麦克风，嘴永远跑在补救前面。',
    dimensionBias: ['filter', 'spark'],
    // filter 在这里代表低filter（选了filter:-1 的选项）
    // 实际匹配会用 negFilter 逻辑
    mbtiAffinity: ['ESTP', 'ENTP', 'ESFP'],
  },
  {
    id: 'soft-tyrant',
    code: 'SOFT',
    title: '温柔独裁者',
    hook: '你说话不大声，但事情最后通常都会按你的意思走。',
    systemRemark: '系统检测到你具备高级别的温和掌控欲。',
    friendshipWarning: '朋友会觉得是自己做的决定，其实大多是你铺好的轨道。',
    selfAwareDisclaimer: '你不爱硬压，你更爱让别人自己走向你的结论。',
    shareSnippet: '我是 NBTI 的温柔独裁者，不吵不闹但方向归我。',
    dimensionBias: ['gravity', 'trap'],
    mbtiAffinity: ['INFJ', 'ENFJ', 'INTJ'],
  },
  {
    id: 'public-candle',
    code: 'CAND',
    title: '人群蜡烛芯',
    hook: '你走到哪都容易把别人情绪点亮，也容易把局烧旺。',
    systemRemark: '系统判断你具有高社交点火率。',
    friendshipWarning: '朋友跟你待久了会很快乐，也会很累。',
    selfAwareDisclaimer: '你没有恶意，你只是有点太会带节奏。',
    shareSnippet: '我是 NBTI 的人群蜡烛芯，场子不亮我就想点火。',
    dimensionBias: ['orbit', 'spark'],
    mbtiAffinity: ['ENFP', 'ESFP', 'ENFJ'],
  },
  {
    id: 'petty-archivist',
    code: 'ARCH',
    title: '小心眼档案员',
    hook: '你原谅别人要看版本记录，而不是看对方语气。',
    systemRemark: '系统判断你拥有异常完整的旧账检索能力。',
    friendshipWarning: '朋友最怕你突然说出"三个月前你也这样"。',
    selfAwareDisclaimer: '你不是坏，你只是记忆力带点情绪保鲜功能。',
    shareSnippet: '我是 NBTI 的小心眼档案员，不记仇，我只是记得细。',
    dimensionBias: ['spite', 'gravity'],
    mbtiAffinity: ['ISTJ', 'ISFJ', 'ESTJ'],
  },
  {
    id: 'absurd-engine',
    code: 'ABSR',
    title: '荒谬发动机',
    hook: '你不一定靠谱，但你一定能把日子过出离谱的记忆点。',
    systemRemark: '系统确认你思路经常绕开常规车道。',
    friendshipWarning: '朋友跟你相处最大的风险，是故事会越讲越像编的。',
    selfAwareDisclaimer: '你不是乱来，你只是相信生活需要一点失真。',
    shareSnippet: '我是 NBTI 的荒谬发动机，现实到我这儿都会拐个弯。',
    dimensionBias: ['absurdity', 'chaos'],
    mbtiAffinity: ['ENTP', 'ENFP', 'INTP'],
  },
  {
    id: 'silent-auditor',
    code: 'AUDT',
    title: '静音审计员',
    hook: '你不打断任何人，但你会在心里给所有人打分。',
    systemRemark: '系统判断你具备高密度观察与低频发言特征。',
    friendshipWarning: '朋友通常不知道自己什么时候已经进入你的评估期。',
    selfAwareDisclaimer: '你安静不代表你放空，很多时候你只是在记录。',
    shareSnippet: '我是 NBTI 的静音审计员，话少，但观察从不缺席。',
    dimensionBias: ['judge', 'mask'],
    mbtiAffinity: ['INFJ', 'INTP', 'ISTP'],
  },
  {
    id: 'kind-chaos',
    code: 'KCHA',
    title: '善意搅局人',
    hook: '你本意是帮忙，结果经常把局面直接升级成连续剧。',
    systemRemark: '系统检测到你干预事务时常伴随戏剧性增幅。',
    friendshipWarning: '朋友会感谢你的热心，但也会偷偷祈祷你别太投入。',
    selfAwareDisclaimer: '你不是添乱，你只是热心和失控常常同框。',
    shareSnippet: '我是 NBTI 的善意搅局人，帮忙这件事我做得很有节目性。',
    dimensionBias: ['chaos', 'spark'],
    mbtiAffinity: ['ESFJ', 'ENFP', 'ESFP'],
  },
  {
    id: 'solo-satellite',
    code: 'SOLO',
    title: '单飞卫星',
    hook: '你不是不会社交，你只是懒得一直围着别人公转。',
    systemRemark: '系统判断你拥有稳定的独处充电和低噪偏好。',
    friendshipWarning: '朋友需要知道，你消失一下多半不是生气，是续航。',
    selfAwareDisclaimer: '你不是冷漠，你只是对高频社交没有长期订阅欲。',
    shareSnippet: '我是 NBTI 的单飞卫星，会回来，但先让我离群一会儿。',
    dimensionBias: ['filter', 'bunker'],
    mbtiAffinity: ['INTP', 'ISTP', 'INFP'],
  },
  {
    id: 'venom-tongue',
    code: 'VENM',
    title: '毒舌刺客',
    hook: '你说话像在写讣告，每一句都让人想原地去世。',
    systemRemark: '系统判定你具备语言级别的化学攻击能力。',
    friendshipWarning: '朋友跟你聊天像在扫雷，不知道哪句会触发你的台词杀。',
    selfAwareDisclaimer: '你不是在伤害，你只是在锻炼别人的心脏。',
    shareSnippet: '我是 NBTI 的毒舌刺客，开口就是暴击。',
    dimensionBias: ['venom', 'pride'],
    mbtiAffinity: ['ESTJ', 'ENTJ', 'ESTP'],
  },
  {
    id: 'iron-turtle',
    code: 'TRTL',
    title: '铁甲乌龟',
    hook: '你看起来人畜无害，但别人刚开口你就已经在想怎么反驳。',
    systemRemark: '系统检测到你的防御塔已经堆到外太空。',
    friendshipWarning: '想听到你的真心话？先打破你的防御再说。',
    selfAwareDisclaimer: '你是谨慎，不是怂，只是子弹上膛比较慢。',
    shareSnippet: '我是 NBTI 的铁甲乌龟，壳有多厚你自己知道。',
    dimensionBias: ['bunker', 'judge'],
    mbtiAffinity: ['ISFJ', 'ISTJ', 'ISFP'],
  },
  {
    id: 'speed-demon',
    code: 'SPED',
    title: '上头怪咖',
    hook: '你做事像开挂，想法和行动之间基本没有缓冲带。',
    systemRemark: '系统确认你的人生字典里没有"等等"这个词。',
    friendshipWarning: '朋友和你一起做决定，经常在事后才意识到刚才经历了什么。',
    selfAwareDisclaimer: '你不是冲动，你只是觉得想清楚的时间成本太贵。',
    shareSnippet: '我是 NBTI 的上头怪咖，先干再说的典型代表。',
    dimensionBias: ['speed', 'chaos'],
    mbtiAffinity: ['ESTP', 'ENTP', 'ISTP'],
  },
  {
    id: 'trap-weaver',
    code: 'TRAP',
    title: '陷阱织女',
    hook: '你说话像在下棋，每句都有伏笔，听懂的人后背发凉。',
    systemRemark: '系统判定你具备语言级别的陷阱设计能力。',
    friendshipWarning: '和你对话像在参加陷阱解密，答错了就等着被绕进去。',
    selfAwareDisclaimer: '你不是在套路，你只是在测试对方的智商。',
    shareSnippet: '我是 NBTI 的陷阱织女，说话和下棋一样。',
    dimensionBias: ['trap', 'mask'],
    mbtiAffinity: ['INFP', 'INFJ', 'INTJ'],
  },
];